use crate::test::test_instruction;

#[test]
fn test_bin() {
    let textual_repr = r#"
        (module
            (func (export "zkmain")
                (i32.const 1)
                (i32.const 1)
                (i32.add)
                (drop)
                (i32.const 1)
                (i32.const 4294967295)
                (i32.add)
                (drop)

                (i64.const 1)
                (i64.const 1)
                (i64.add)
                (drop)
                (i64.const 1)
                (i64.const 18446744073709551615)
                (i64.add)
                (drop)

                (i32.const 1)
                (i32.const 1)
                (i32.sub)
                (drop)
                (i32.const 0)
                (i32.const 1)
                (i32.sub)
                (drop)

                (i64.const 1)
                (i64.const 1)
                (i64.sub)
                (drop)
                (i64.const 0)
                (i64.const 1)
                (i64.sub)
                (drop)

                (i32.const 4)
                (i32.const 3)
                (i32.mul)
                (drop)
                (i32.const 4294967295)
                (i32.const 4294967295)
                (i32.mul)
                (drop)

                (i64.const 4)
                (i64.const 3)
                (i64.mul)
                (drop)
                (i64.const 18446744073709551615)
                (i64.const 18446744073709551615)
                (i64.mul)
                (drop)

                (i32.const 4)
                (i32.const 3)
                (i32.div_u)
                (drop)
                (i32.const 4)
                (i32.const 4)
                (i32.div_u)
                (drop)
                (i32.const 0x80000000)
                (i32.const 1)
                (i32.div_u)
                (drop)

                (i64.const 4)
                (i64.const 3)
                (i64.div_u)
                (drop)
                (i64.const 4)
                (i64.const 4)
                (i64.div_u)
                (drop)
                (i64.const 0x8000000000000000)
                (i64.const 1)
                (i64.div_u)
                (drop)

                (i32.const 4)
                (i32.const 3)
                (i32.div_s)
                (drop)
                (i32.const -4)
                (i32.const -3)
                (i32.div_s)
                (drop)
                (i32.const -4)
                (i32.const 3)
                (i32.div_s)
                (drop)
                (i32.const 4)
                (i32.const -3)
                (i32.div_s)
                (drop)
                (i32.const -3)
                (i32.const 4)
                (i32.div_s)
                (drop)
                (i32.const 0x80000000)
                (i32.const 1)
                (i32.div_s)
                (drop)

                (i64.const 4)
                (i64.const 3)
                (i64.div_s)
                (drop)
                (i64.const -4)
                (i64.const -3)
                (i64.div_s)
                (drop)
                (i64.const -4)
                (i64.const 3)
                (i64.div_s)
                (drop)
                (i64.const 4)
                (i64.const -3)
                (i64.div_s)
                (drop)
                (i64.const -3)
                (i64.const 4)
                (i64.div_s)
                (drop)
                (i64.const 0x8000000000000000)
                (i64.const 1)
                (i64.div_s)
                (drop)

                (i32.const 4)
                (i32.const 3)
                (i32.rem_u)
                (drop)
                (i32.const 4)
                (i32.const 4)
                (i32.rem_u)
                (drop)

                (i64.const 4)
                (i64.const 3)
                (i64.rem_u)
                (drop)
                (i64.const 4)
                (i64.const 4)
                (i64.rem_u)
                (drop)

                (i32.const 4)
                (i32.const 3)
                (i32.rem_s)
                (drop)
                (i32.const -4)
                (i32.const -3)
                (i32.rem_s)
                (drop)
                (i32.const -4)
                (i32.const 3)
                (i32.rem_s)
                (drop)
                (i32.const 4)
                (i32.const -3)
                (i32.rem_s)
                (drop)
                (i32.const 4)
                (i32.const -4)
                (i32.rem_s)
                (drop)

                (i64.const 4)
                (i64.const 3)
                (i64.rem_s)
                (drop)
                (i64.const -4)
                (i64.const -3)
                (i64.rem_s)
                (drop)
                (i64.const -4)
                (i64.const 3)
                (i64.rem_s)
                (drop)
                (i64.const 4)
                (i64.const -3)
                (i64.rem_s)
                (drop)
                (i64.const 4)
                (i64.const -4)
                (i64.rem_s)
                (drop)
            )
        )
        "#;

    test_instruction(textual_repr).unwrap()
}

#[test]
fn test_bin_uniarg() {
    let textual_repr = r#"
    (module
        (func (export "zkmain")
            (local i32)

            (i32.const 1)
            (i32.const 2)
            (i32.add)
            (drop)

            (local.get 0)
            (i32.const 1)
            (i32.add)
            (drop)

            (i32.const 1)
            (local.get 0)
            (i32.add)
            (drop)

            (i32.const 0)
            (i32.const 1)
            (i32.const 2)
            (i32.add)
            (i32.add)
            (drop)

            (i32.const 0)
            (i32.const 1)
            (i32.add)
            (i32.const 2)
            (i32.add)
            (drop)
        )
    )
    "#;

    test_instruction(textual_repr).unwrap()
}
