name: rust-build

on:
  pull_request:
    branches: [ "**" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with: 
        submodules: recursive
    - uses: actions-rs/toolchain@v1
      with:
        components: rustfmt, clippy
    - name: Code Style Check
      run: cargo fmt --check
    - name: Cargo clippy
      run: cargo clippy && cargo clippy --features continuation
    - name: Build
      run: cargo build && cargo clean
    - name: Build Playground
      working-directory: ./crates/playground
      run: cargo build --examples
